stages:
  - build

flatpak-build:
  stage: build
  image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:3.28
  only:
    refs:
    - master
    - /^staging/.*$/
    - /^flatpak/.*$/

  variables:
    APP_ID: "org.freedesktop.Bustle"
    BUNDLE: "${APP_ID}.flatpak"
    REPO: "repo"
    RUNTIME_REPO: "https://flathub.org/repo/flathub.flatpakrepo"

  script:
    - flatpak-builder --repo ${REPO} app flatpak/${APP_ID}.yaml
    - flatpak build-bundle --runtime-repo=${RUNTIME_REPO} ${REPO} ${BUNDLE} ${APP_ID}

  artifacts:
    paths:
      - ${BUNDLE}
    expire_in: 30 days

  cache:
    key: "flatpak-builder-cache"
    paths:
      - .flatpak-builder/cache
